### ISSUE TITLE
docker: simplify layers

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-message-broker#3]
`Dockerfile` uses too much separate `RUN` commands. They should be chained to reduce the number of image layers.

**Comment by tiborsimko** [comment]
Actually, instead of `FROM ubuntu:16.04` we should start from `rabbitmq` official docker image... much smaller.

**Comment by hjhsalo** [comment]
Should we use a Debian Linux or Alpine Linux -based image?
Have you been in favor of Debian-based images in the past?

Comparing size (downloaded image, all layers, not compressed) of rabbitmq:3.6 and rabbitmq:3.6-alpine, Alpine-based image is approx. 1/5 from size of Debian-based one:

| Image                        | SHA                  | Updated      | Size        |
| -------------------------- |:-------------------:|:---------------:|------------:|
| rabbitmq:3.6              | 8cdcbee37f62  | 7 days ago   | 179 MB  |
| rabbitmq:3.6-alpine   | 1a4b5e026afe  | 11 days ago | 37.5 MB |

Given that we probably don't need to customize the image by installing packets or binaries (or do we?) I would give the Alpine-based one a try. Let's change to Debian-based if we run into maintenance or customizing issues later on?

**Comment by tiborsimko** [comment]
Closing due to forthcoming MQ changes.
