### ISSUE TITLE
admin: facilitate queue manipulations

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-message-broker#45]
**Current status**

When something unexpected happens such as a message that is constantly requeued, see the situation observed with 0.8.0 and described in https://github.com/reanahub/reana-server/issues/436, the admins may want to remove the problematic message from the queue.

Currently it is not easy, because while one can launch `rabbitmqctl`:

```console
$ kubectl exec -i -t reana-message-broker-0 -- rabbitmqctl list_queues
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name    messages
workflow-submission     24
jobs-status     0
```

one cannot launch `rabbitmqadmin`:

```console
$ kubectl exec -i -t reana-message-broker-0 -- rabbitmqadmin list queues
*** Could not connect: [Errno 111] Connection refused

command terminated with exit code 1
```

One cannot easily act on queue content.

**Expected behaviour**

It would be useful to have a way to manipulate queues in case of emergency, e.g. to list and delete certain messages.

There are two possibilities:

1. Allow `rabbitmqadmin` and configure proper secrets.  In this way, MQ and DB will be treated the same, so that cluster admins could launch (SQL and MQ) commands to inspect/change/whatever in the DB and MQ services.

2. Provide recipe e.g. a standalone python code snippet to be run from `r-server scheduler` container that would list/remove/act-upon messages in the queue. So that admins wouldn't use `rabbitmqadmin` and friends, but rather our own python snippets  from `r-server` pod.

**Comment by VMois** [comment]
It is not possible to delete a specific message from the queue using `rabbitmqadmin`. Overall, RabbitMQ doesn't support this.

An alternative is to develop a script where you can define, for example, `workflow_uuid` that corresponds to the message you want to delete. The script will consume all messages. If it will find the desired one it will `ack` it, all others will be re-queued.

**Comment by VMois** [comment]
To list messages in the queued, `rabbitmqadmin` needs to be enabled. 

*Note:* the messages list operation means getting messages, listing them, and publishing them again.

**Comment by audrium** [comment]
One possibility to do it using `rabbitmqadmin` would be to list all messages in the queue ("Get messages"), `ack` it and republish only the ones that do not cause any troubles. Just verified that it works:
![Screenshot from 2022-04-26 16-56-20](https://user-images.githubusercontent.com/4990025/165329796-46bcf213-3b86-4248-836a-fd237a2ca043.png)

Could be a solution when there are a few messages in the queue, however for lots of messages it's a bit too much manual labor, since it requires copying the message payload, selecting `Delivery mode` and specifying priority..

**Comment by tiborsimko** [comment]
WRT recipe, a simple one added to the wiki as a tip. https://github.com/reanahub/reana/wiki/Tips-for-RabbitMQ#Acknowledge-messages

**Comment by VMois** [comment]
Found [rabtap](https://github.com/jandelgado/rabtap) - CLI tool for RabbitMQ written in Golang. It has some nice capabilities but still doesn't allow to delete messages from the queue.

I think the reason behind this is that different users have different formats (JSON, Msgpack) and identifiers (in our case `workflow_id`) for messages so creating a general tool can be challenging.
